Repository tenjin/tenjin-android-sdk, pull requests merged in 2022-06, with the labels that each got.

#91 [TENJIN-12272] Update summary in README.md file
  README.md
Labels: enhancement

#92 Added release notes for 1.12.15
  RELEASE_NOTES.md
  tenjin.aar
  tenjin.jar
Labels: bug

#93 [TENJIN-12138] - Fix release artefacts of 1.12.15
  tenjin.aar
  tenjin.jar
Labels: release fix
